version: '2'

services:
  php-wikia:
    image: php-wikia-apache
    ports:
      - "80:80"
    volumes:
      - ../../../app:/var/www/html
      - ../../../config:/var/www/config
      - ../../../cache:/var/www/cache/messages
    depends_on:
      - memcached
    environment:
      - MEMCACHED_SERVER=memcached:11211
      - WIKIA_DATACENTER=poz
      - WIKIA_ENVIRONMENT=dev
      - WIKIA_DEV_DOMAIN=dev.wikia-local.com
  memcached:
    image: memcached:alpine
