language: php

php:
  - 7
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  - nightly

before_install: 
  - cd $TRAVIS_BUILD_DIR/extensions/VisualEditor/
  - npm install grunt-cli
  - cd $TRAVIS_BUILD_DIR/extensions/VisualEditor/lib/ve/
  - npm install grunt-cli
install:
  - cd $TRAVIS_BUILD_DIR/
  - travis_retry composer update --no-progress --prefer-dist --profile -v -n --verbose
  - cd $TRAVIS_BUILD_DIR/
  - npm install
  - cd $TRAVIS_BUILD_DIR/extensions/VisualEditor/
  - npm install
  - cd $TRAVIS_BUILD_DIR/extensions/VisualEditor/lib/ve/
  - npm install
before_script: 
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd $TRAVIS_BUILD_DIR/extensions/VisualEditor/
  - grunt build
  - cd $TRAVIS_BUILD_DIR/extensions/VisualEditor/lib/ve/
  - grunt build
script:
  - cd $TRAVIS_BUILD_DIR/
  - composer test
  - cd $TRAVIS_BUILD_DIR/
  - npm test
  - cd $TRAVIS_BUILD_DIR/extensions/VisualEditor/
  - npm test
  - cd $TRAVIS_BUILD_DIR/extensions/VisualEditor/lib/ve/
  - npm test
