language: php
php: 7.3
dist: xenial
sudo: required

addons:
  apt:
    sources:
      # https://launchpad.net/~jbboehr/+archive/ubuntu/mustache
      - sourceline: "deb http://ppa.launchpad.net/jbboehr/mustache/ubuntu xenial main"
        key_url: "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x7DAD64617A3EC228D368C50F9A90195D619F9E2B"
    packages:
      - libmustache-dev
      - rabbitmq-server  # https://travis-ci.community/t/rabbitmq-on-xenial/1827

services:
  - mysql  # https://docs.travis-ci.com/user/database-setup/#mysql

install:
  - pecl channel-update pecl.php.net
  - wget https://pecl.php.net/get/mustache-0.8.1.tgz && pecl install mustache-0.8.1.tgz
  - wget https://pecl.php.net/get/uopz-6.0.1.tgz && pecl install uopz-6.0.1.tgz
  - php -v && php -m
before_script:
  # make sure indices are upgraded, see https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-23.html#mysqld-5-7-23-bug
  - sudo mysql_upgrade
  - phpenv config-add tests/travis/php.ini
script:
  - git diff $TRAVIS_BRANCH..HEAD --name-only --diff-filter ACMRT | grep \.php$ | grep -Ev '(lib/composer|lib/Swagger|/templates/)' | xargs -n 1 php -l
  - cd tests && ./php-tests.sh

notifications:
  email: false
