apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-sandbox
  namespace: prod
  labels:
    app: mediawiki-sandbox
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mediawiki-sandbox
  template:
    metadata:
      labels:
        app: mediawiki-sandbox
    spec:
      containers:
        - name: nginx
          image: artifactory.wikia-inc.com/sus/mediawiki-sandbox-nginx:latest
          ports:
            - containerPort: 8080
        - name: php
          image: artifactory.wikia-inc.com/sus/mediawiki-sandbox-php:latest
          env:
            - name: WIKIA_DATACENTER
              value: "sjc"
            - name: WIKIA_ENVIRONMENT
              value: "sandbox"
            - name: HOSTNAME_OVERRIDE
              value: "sandbox-sus2"
            - name: LOG_SOCKET_ONLY
              value: "yes"
            - name: LOG_SOCKET_ADDRESS
              value: "tcp://localhost:9999"
          resources:
            limits:
              cpu: "1"
              memory: "1300Mi"
            requests:
              cpu: "400m"
              memory: "800Mi"
        # MW log output, see K8s_LOGGING.md
        - name: logger
          image: artifactory.wikia-inc.com/sus/mediawiki-logger:latest
---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-sandbox
spec:
  selector:
    app: mediawiki-sandbox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mediawiki-sandbox-ingress
spec:
  rules:
    - host: "sandbox-sus2.prod.sjc.k8s.wikia.net"
      http:
        paths:
          - path: /
            backend:
              serviceName: mediawiki-sandbox
              servicePort: 80
