apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-nginx-test
  namespace: dev
  labels:
    app: php-nginx-test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-wikia-dev
  template:
    metadata:
      labels:
        app: nginx-wikia-dev
    spec:
      containers:
        - name: nginx
          image: artifactory.wikia-inc.com/sus/nginx-wikia-dev:latest
          ports:
            - containerPort: 8080
        - name: php
          image: artifactory.wikia-inc.com/sus/php-wikia-k8s:latest
          env:
            - name: WIKIA_DATACENTER
              value: "poz"
            - name: WIKIA_ENVIRONMENT
              value: "dev"
            - name: WIKIA_DEV_DOMAIN
              value: "wiki.poz-dev.k8s.wikia.net"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-wikia-dev
spec:
  selector:
    app: nginx-wikia-dev
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: php-nginx-test-ingress
spec:
  rules:
    - host: "*.wiki.poz-dev.k8s.wikia.net"
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx-wikia-dev
              servicePort: 8080
    - host: "wiki.poz-dev.k8s.wikia.net"
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx-wikia-dev
              servicePort: 8080
